Fix printing posts without URL.
Fixes: commit 5cd224b46965dda28ee5178c7d7def6f24cf87bc
       ("Spin off Origin.")

Fixes:

    $ zygolophodon https://mastodon.social/@http@infosec.exchange
    ...
    Traceback (most recent call last):
      ...
      File ".../zygolophodon", line 872, in fix_post
        if post.url.startswith(f'{self.url}/'):
           ^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'startswith'