lib.html: fix handling <a> without href.
Before:

    >>> import lib.html
    >>> lib.html.fmt_html('<a>spam</a>')
    '[spam]<>\n'

After:

    >>> lib.html.fmt_html('<a>spam</a>')
    'spam\n'

Fixes:

    $ zygolophodon https://donotsta.re/notice/B13iBMFzmX7EbbFpzs
    Location: https://donotsta.re/notice/B13iBMFzmX7EbbFpzs
    Origin: https://chilemasto.casa/@pomelo/115687388506195446
    ...
    Traceback (most recent call last):
      File ".../zygolophodon/zygolophodon", line 24, in <module>
        lib.cli.main()
      File ".../zygolophodon/lib/cli.py", line 315, in main
        xmain()
      File ".../zygolophodon/lib/cli.py", line 161, in xmain
        process_post(instance, post_id=match.ident,
      File ".../zygolophodon/lib/cli.py", line 233, in process_post
        print_post(post, hide_in_reply_to=with_ancestors)
      File ".../zygolophodon/lib/cli.py", line 298, in print_post
        text = fmt_html(post.content)
               ^^^^^^^^^^^^^^^^^^^^^^
      File ".../zygolophodon/lib/html.py", line 119, in fmt_html
        text = re.sub('\N{STX}(.*?)\N{ETX}', repl, text, flags=re.DOTALL)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
        return _compile(pattern, flags).sub(repl, string, count)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File ".../zygolophodon/lib/html.py", line 118, in repl
        return fmt_url(url)
               ^^^^^^^^^^^^
      File ".../zygolophodon/lib/cli.py", line 47, in fmt_url
        raise ValueError('missing URL with no fallback')
    ValueError: missing URL with no fallback

https://github.com/jwilk/zygolophodon/issues/15