Use os.kill() instead of signal.raise_signal().
signal.raise_signal() is available only since Python 3.8.

Fixes:

    AttributeError: module 'signal' has no attribute 'raise_signal'